//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Manager_By_Neimark.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string LastAccessedFolder {
            get {
                return ((string)(this["LastAccessedFolder"]));
            }
            set {
                this["LastAccessedFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MP4</string>
  <string>MKV</string>
  <string>AVI</string>
  <string>WMV</string>
  <string>FLV</string>
  <string>MOV</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultVideoExtensionsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultVideoExtensionsList"]));
            }
            set {
                this["DefaultVideoExtensionsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MP4</string>
  <string>MKV</string>
  <string>AVI</string>
  <string>WMV</string>
  <string>FLV</string>
  <string>MOV</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoExtensionsToScan {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoExtensionsToScan"]));
            }
            set {
                this["VideoExtensionsToScan"] = value;
            }
        }
    }
}
